### ISSUE TITLE
文字列と数字が出たときに止まる

### ISSUE THREAD

**Issue by nabefuta220** [TUT-class-sato/SDM-report2#125]
マイルストーン: 

a=0, b='a'などのように、数字と文字列が入力として与えられたときにValueErrorが出る

----

### エラーログ(その中の一つ)

```bash
ERROR: test_both_invalid (test_all_patterns.TestCalc) (a=0, b='a')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/nabefuta/Windows-SSD/Users/nabe_/デスクトップ/toyoshshiUT/lecture/SoftwareDesignMethodology/SDM-report2/test_all_patterns.py", line 42, in test_both_invalid
    self.assertEqual(a*b, calc(a, b))
  File "/media/nabefuta/Windows-SSD/Users/nabe_/デスクトップ/toyoshshiUT/lecture/SoftwareDesignMethodology/SDM-report2/calc_mul.py", line 11, in calc
    b=float(bi)
ValueError: could not convert string to float: 'a'
```

```bash
ERROR: test_both_invalid (test_all_patterns.TestCalc) (a='a', b=0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/nabefuta/Windows-SSD/Users/nabe_/デスクトップ/toyoshshiUT/lecture/SoftwareDesignMethodology/SDM-report2/test_all_patterns.py", line 42, in test_both_invalid
    self.assertEqual(a*b, calc(a, b))
  File "/media/nabefuta/Windows-SSD/Users/nabe_/デスクトップ/toyoshshiUT/lecture/SoftwareDesignMethodology/SDM-report2/calc_mul.py", line 10, in calc
    a=float(ai)
ValueError: could not convert string to float: 'a'
```

**Comment by nabefuta220** [comment]
すいません、別のレポジトリで投げるはずのissueを投げてしまいました。
