### ISSUE TITLE
calc_mul.py のmatchstringがうまく機能していない?

### ISSUE THREAD

**Issue by nabefuta220** [TUT-class-sato/SDM-report2#137]
(課題とは全く関係がないため、ここで共有させていただきます)

calc_mul.py のmainメソッドについて、標準入力に`'end'`という文字列が入ったら終了すると意図していると思われるが、実際は、whileブロック中でmatchstringは何も使われていないため、Ctrl+Cを押すなどして、何らかの例外を発生させないとプログラムが終了しない。

(実行のログ)

```bash
nabefuta@nabefuta-Yoga-Slim-7-Carbon-13ITL5:~/Desktop/toyohashiUT/lecture/SoftwareDesignMethodology/SDM-report2$ python3 calc_mul.py 
input A: 2 
input B: 3
input A * input B =  6.0
input A: end
input B: end
input A * input B =  -1
input A: ^CTraceback (most recent call last):
  File "/media/nabefuta/Windows-SSD/Users/nabe_/デスクトップ/toyoshshiUT/lecture/SoftwareDesignMethodology/SDM-report2/calc_mul.py", line 34, in <module>
    main()
  File "/media/nabefuta/Windows-SSD/Users/nabe_/デスクトップ/toyoshshiUT/lecture/SoftwareDesignMethodology/SDM-report2/calc_mul.py", line 29, in main
    A = input ('input A: ')
KeyboardInterrupt
```

**Comment by YukinoriSato** [comment]
はい、ご指摘のように、現状では意図した動作がされていない雰囲気な無意味な記述になっております。この点は、私の実装のミスでした。今回は、課題とは関係ないので、この実装のままでテストケースを作成するでお願いします。
